"""initial_schema

Revision ID: 0a0471e92ec1
Revises: 
Create Date: 2026-09-13 04:46:36.242512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0471e92ec1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('employment_status', sa.Enum('EMPLOYED', 'SELF_EMPLOYED', 'UNEMPLOYED', 'RETIRED', 'STUDENT', name='employmentstatus'), nullable=True),
    sa.Column('income_bracket', sa.String(length=40), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('checking_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('savings_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('overdraft_count_30d', sa.Integer(), nullable=False),
    sa.Column('large_withdrawal_flag', sa.Boolean(), nullable=False),
    sa.Column('salary_deposit_detected', sa.Boolean(), nullable=False),
    sa.Column('app_logins_30d', sa.Integer(), nullable=False),
    sa.Column('support_contacts_30d', sa.Integer(), nullable=False),
    sa.Column('hardship_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.Enum('MORTGAGE', 'PERSONAL_LOAN', 'CREDIT_CARD', 'AUTO_LOAN', name='producttype'), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Enum('APP', 'BRANCH', 'ATM', 'CALL_CENTER', 'WEB', name='channel'), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('consecutive_partial_payments', sa.Integer(), nullable=False),
    sa.Column('missed_payment_streak', sa.Integer(), nullable=False),
    sa.Column('avg_days_late_90d', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('debt_to_income_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('credit_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('balance_trend_30d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('early_warning_flag', sa.Boolean(), nullable=False),
    sa.Column('defaulted', sa.Boolean(), nullable=False),
    sa.Column('days_to_default', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('was_flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_payment_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outstanding_balance_after', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('late_fee_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interest_accrued', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('billing_cycle_start', sa.Date(), nullable=True),
    sa.Column('billing_cycle_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ON_TIME', 'LATE', 'PARTIAL', 'MISSED', 'REVERSED', 'GRACE_PERIOD', name='paymentstatus'), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('AUTO_DEBIT', 'TRANSFER', 'CASH', 'CARD', 'THIRD_PARTY', name='paymentmethod'), nullable=True),
    sa.Column('channel', sa.Enum('APP', 'BRANCH', 'ATM', 'CALL_CENTER', 'WEB', name='channel'), nullable=True),
    sa.Column('is_partial_payment', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('messages')
    op.drop_table('risk_features')
    op.drop_table('conversations')
    op.drop_table('accounts')
    op.drop_table('account_activity')
    op.drop_table('customers')
    # ### end Alembic commands ###
